const themes = [
  {
    name: 'base',
    description: 'Clean and neutral basic theme',
    bgColor: '#F5F5F5',
    bgPattern: 'base.svg',
    bgPatternOpacity: 1,
    textColor: '#212121',
    button: {
      bgColor: '#757575',
      textColor: '#FFFFFF',
    },
    chart: {
      setup: '#9E9E9E',
      round: '#616161',
      rest: '#CFD8DC',
    },
  },
  {
    name: 'dark',
    description: 'Dark mode theme for reduced eye strain',
    bgColor: '#121212',
    bgPattern: 'dark.svg',
    bgPatternOpacity: 1,
    textColor: '#E0E0E0',
    button: {
      bgColor: '#A0A0A0',
      textColor: '#212121',
    },
    chart: {
      setup: '#616161',
      round: '#9E9E9E',
      rest: '#424242',
    },
  },
  {
    name: 'linen',
    description: 'Natural olive green mix',
    bgColor: '#F5F5F5',
    bgPattern: 'linen.svg',
    bgPatternOpacity: 1,
    textColor: '#212121',
    button: {
      bgColor: '#5C6F68',
      textColor: '#FDFCF9',
    },
    chart: {
      setup: '#A7B9AC',
      round: '#5C6F68',
      rest: '#D7E0DC',
    },
  },
  {
    name: 'leaflight',
    description: 'Refreshing lime green atmosphere',
    bgColor: '#F1F8E9',
    bgPattern: 'leaflight.svg',
    bgPatternOpacity: 1,
    textColor: '#2E3B2C',
    button: {
      bgColor: '#8BC34A',
      textColor: '#FFFFFF',
    },
    chart: {
      setup: '#00C853',
      rest: '#2979FF',
      round: '#D50000',
    },
  },
  {
    name: 'umber',
    description: 'Deep purple with premium feel',
    bgColor: '#1C1C1E',
    bgPattern: 'umber.svg',
    bgPatternOpacity: 1,
    textColor: '#D6D6D6',
    button: {
      bgColor: '#5E35B1',
      textColor: '#EDE7F6',
    },
    chart: {
      setup: '#7C4DFF',
      round: '#512DA8',
      rest: '#9575CD',
    },
  },
  {
    name: 'metro',
    description: 'Midnight blue with modern aesthetic',
    bgColor: '#0D1B2A',
    bgPattern: 'metro.svg',
    bgPatternOpacity: 1,
    textColor: '#E0F2F1',
    button: {
      bgColor: '#00ACC1',
      textColor: '#E0F2F1',
    },
    chart: {
      setup: '#00ACC1',
      round: '#00838F',
      rest: '#26C6DA',
    },
  },
  {
    name: 'azure',
    description: 'Refreshing sky blue summer vibe',
    bgColor: '#E0F7FA',
    bgPattern: 'azure.svg',
    bgPatternOpacity: 1,
    textColor: '#004D40',
    button: {
      bgColor: '#26A69A',
      textColor: '#E0F7FA',
    },
    chart: {
      setup: '#00BFA5',
      round: '#0288D1',
      rest: '#4DD0E1',
    },
  },
  {
    name: 'brasa',
    description: 'Passionate orange-red energy',
    bgColor: '#BF360C',
    bgPattern: 'brasa.svg',
    bgPatternOpacity: 1,
    textColor: '#FFF3E0',
    button: {
      bgColor: '#FFCCBC',
      textColor: '#BF360C',
    },
    chart: {
      setup: '#FBC02D',
      round: '#8B2C17',
      rest: '#FF7043',
    },
  },
  {
    name: 'vanta',
    description: 'Minimal black & white contrast',
    bgColor: '#121212',
    bgPattern: 'vanta.svg',
    bgPatternOpacity: 1,
    textColor: '#E0E0E0',
    button: {
      bgColor: '#FAFAFA',
      textColor: '#121212',
    },
    chart: {
      setup: '#424242',
      round: '#757575',
      rest: '#9E9E9E',
    },
  },
  {
    name: 'lucid',
    description: 'Cool blue-gray clear focus',
    bgColor: '#ECEFF1',
    bgPattern: 'lucid.svg',
    bgPatternOpacity: 1,
    textColor: '#263238',
    chart: {
      setup: '#607D8B',
      round: '#455A64',
      rest: '#90A4AE',
    },
    button: {
      bgColor: '#546E7A',
      textColor: '#ECEFF1',
    },
  },
  {
    name: 'mellow',
    description: 'Warm yellow sunshine energy',
    bgColor: '#FFFDE7',
    bgPattern: 'mellow.svg',
    bgPatternOpacity: 1,
    textColor: '#5D4037',
    chart: {
      setup: '#FFCA28',
      round: '#F57F17',
      rest: '#FFE082',
    },
    button: {
      bgColor: '#FFB300',
      textColor: '#FFFDE7',
    },
  },
  {
    name: 'noctis',
    description: 'Mysterious purple cosmic atmosphere',
    bgColor: '#1A1446',
    bgPattern: 'noctis.svg',
    bgPatternOpacity: 1,
    textColor: '#D1C4E9',
    chart: {
      setup: '#7E57C2',
      round: '#512DA8',
      rest: '#9575CD',
    },
    button: {
      bgColor: '#7C4DFF',
      textColor: '#EDE7F6',
    },
  },
  {
    name: 'beast',
    description: 'Powerful black & red contrast',
    bgColor: '#1B1B1B',
    bgPattern: 'beast.svg',
    bgPatternOpacity: 1,
    textColor: '#FAFAFA',
    button: {
      bgColor: '#D32F2F',
      textColor: '#FFFFFF',
    },
    chart: {
      setup: '#F57C00',
      round: '#B71C1C',
      rest: '#757575',
    },
  },
  {
    name: 'boxer',
    description: 'Ringside dark blue & red atmosphere',
    bgColor: '#121721',
    bgPattern: 'boxer.svg',
    bgPatternOpacity: 1,
    textColor: '#ECEFF1',
    button: {
      bgColor: '#546E7A',
      textColor: '#ECEFF1',
    },
    chart: {
      setup: '#546E7A',
      round: '#D32F2F',
      rest: '#90A4AE',
    },
  },
  {
    name: 'ring',
    description: 'Playful boxing doodle pattern',
    bgColor: '#F5F7FA',
    bgPattern: 'boxing.jpg',
    bgPatternOpacity: 0.2,
    textColor: '#2C3E50',
    button: {
      bgColor: '#00ACC1',
      textColor: '#FFFFFF',
    },
    chart: {
      setup: '#66BB6A',
      round: '#EC407A',
      rest: '#42A5F5',
    },
  },
  {
    name: 'yadon',
    description: 'Relaxed pink warmth with cool gray accent',
    bgColor: '#F9E8EA',
    bgPattern: 'yadon.svg',
    bgPatternOpacity: 1,
    textColor: '#5A3D42',
    button: {
      bgColor: '#E88790',
      textColor: '#FFF5F0',
    },
    chart: {
      setup: '#8B8FAF',
      round: '#D4707C',
      rest: '#F2C4A0',
    },
  },
];

export default themes;
